#!/bin/bash

progname="$( basename $0 )"
progdir=$( ( pushd $( dirname $0 ) > /dev/null 2>&1 ; \
    pwd ; popd > /dev/null 2>&1 ) )

user=none
source ${progdir}/trait-options

mkdir -p /home/${user}/.config/autostart
cat <<EOF>  /home/${user}/.config/autostart/firefox.desktop
[Desktop Entry]
Name=Firefox
Encoding=UTF-8
Version=1.0
Exec=/home/${user}/.kablui/runff
EOF
chmod 755 /home/${user}/.config/autostart/firefox.desktop

mkdir -p /home/${user}/.kablui
cat <<EOF>  /home/${user}/.kablui/runff

xdone=0
while ((! \$xdone)); do
    if ( ps auwwxf | grep -q "clock-applet" ); then
        if ( ps auwwxf | grep -q "gnome-power-manager" ); then
            xdone=1
        else
            sleep 1
        fi
    else
        sleep 1
    fi
done
firefox >> /home/${user}/.kablui/runff.log 2>&1 &

EOF
chmod 755 /home/${user}/.kablui/runff

chown -R ${user}:${user} /home/${user}

