#!/bin/bash

progname="$( basename $0 )"
progdir=$( ( pushd $( dirname $0 ) > /dev/null 2>&1 ; \
    pwd ; popd > /dev/null 2>&1 ) )

user=none
source ${progdir}/trait-options

mkdir -p /home/${user}/.config/autostart
cat <<EOF>  /home/${user}/.config/autostart/firefox.desktop
[Desktop Entry]
Name=Firefox
Encoding=UTF-8
Version=1.0
Exec=firefox
EOF
chmod 755 /home/${user}/.config/autostart/firefox.desktop

chown -R ${user}:${user} /home/${user}
