#!/bin/bash

progname="$( basename $0 )"
progdir=$( ( pushd $( dirname $0 ) > /dev/null 2>&1 ; \
    pwd ; popd > /dev/null 2>&1 ) )

user=none
source ${progdir}/trait-options

mkdir -p /home/${user}/.config/autostart
cp /usr/share/applications/mozilla-firefox.desktop /home/${user}/.config/autostart/firefox.desktop

chown -R ${user}:${user} /home/${user}
