#!/bin/bash
#
#############################################################################
#
# functions: utility functions
#
#############################################################################
#
# Copyright 2007-2010 Douglas McClendon <dmc AT filteredperception DOT org>
#
#############################################################################
#
# This file is part of VirOS.
#
#    VirOS is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    VirOS is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with VirOS.  If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################

##
## VirOS funcions
##
## utility functions for viros scripts
##

##
## set default values for undefined globals that are used
##
if [ "x${viros_comtrace}" == "x" ]; then
    # this seems to always be reduntant (but doublecheck before removing comment
#    viros_comtrace="VirOS-${progname}"
    viros_comtrace="VirOS"
fi

if [ "x${vopt_debug}" == "x" ]; then
    vopt_debug=0
fi

if [ "x${vopt_verbose}" == "x" ]; then
    vopt_verbose=0
fi

if [ "x${vopt_quiet}" == "x" ]; then
    vopt_quiet=0
fi

if [ "x${progname}" == "x" ]; then
    progname="vsys functions"
fi

if [ "x${logfiles}" == "x" ]; then
    logfiles="/dev/null"
fi

if [ "x${cleanup_command}" == "x" ]; then
    cleanup_command="echo cleaning up..."
fi

#
# usage: normalize_path <path>
#
# normalize_path will take a path to a file or directory, and return
# an equivalent non-relative (non-symlink?) path
#
# globals used: none
#
function normalize_path {
    result=$( cd $( dirname $1 ) ; pwd )/$( basename $1 )
    if (($?)); then
	die "unexpected problem normalizing path $1"
    else
	echo "$result"
    fi
}


#
# usage: veva command args...
#
# the vsys eval wrapper runs a command, redirecting it's output to 
# a nicely formatted log entry
#
# globals used: progname, logfiles
#
function veva {

    # in debug mode, send debug messages to stdout as well as logfiles
    # (doesn't seem to work tho)
    if (($vopt_debug)); then
	vlogfiles="${logfiles} /dev/stdout"
    else
	vlogfiles="${logfiles}"
    fi

    for logfile in $vlogfiles; do
	echo "========================================================================" >> $logfile
	echo "${progname}: BEGIN $( date +%Y-%m-%d.%H:%M:%S ) veva: $@" >> $logfile
	echo "------------------------------------------------------------------------" >> $logfile
	echo "${progname}: status: $@" >> $logfile
    done

    # I have not yet verified that pipefail is doing what I think its doing
    # (my first ever use of pipefail)
    set -o pipefail
    if (($vopt_debug)); then
	eval $@ 2>&1 | tee -a $logfiles
	retval=$?
    else
	eval $@ 2>&1 | tee -a $logfiles > /dev/null
	retval=$?
    fi
    set +o pipefail

    for logfile in $vlogfiles; do
	echo "------------------------------------------------------------------------" >> $logfile
	echo "${progname}: RV $retval END $( date +%Y-%m-%d.%H:%M:%S ) veva: $@" >> $logfile
	echo "========================================================================" >> $logfile
    done

    return $retval
}

# stupid workaround for my lack of level 99 bash gurudom
# (no doubt I'll find a better method than this at some point)
function vevastupid {

    # in debug mode, send debug messages to stdout as well as logfiles
    # (doesn't seem to work tho)
    if (($vopt_debug)); then
	vlogfiles="${logfiles} /dev/stdout"
    else
	vlogfiles="${logfiles}"
    fi

    for logfile in $vlogfiles; do
	echo "========================================================================" >> $logfile
	echo "${progname}: BEGIN $( date +%Y-%m-%d.%H:%M:%S ) veva: $@" >> $logfile
	echo "------------------------------------------------------------------------" >> $logfile
	echo "${progname}: status: $@" >> $logfile
    done

    for (( i=1 ; $i <= $# ; i=$(( $i + 1 )) )); do
	eval "datcopy[$i]=\$$i"
	if ( echo "${datcopy[$i]}" | grep -q "___" ); then
#	    datcopy[$i]="\"$( echo ${datcopy[$i]} | sed -e 's/VirOS_Synthesis_Monitor/VirOS\ Synthesis\ Monitor/')\""
	    datcopy[$i]="\"$( echo ${datcopy[$i]} | sed -e 's/___/\ /g' )\""
	fi
    done

    # I have not yet verified that pipefail is doing what I think its doing
    # (my first ever use of pipefail)
    set -o pipefail
    if (($vopt_debug)); then
	eval ${datcopy[@]} 2>&1 | tee -a $logfiles
	retval=$?
    else
	eval ${datcopy[@]} 2>&1 | tee -a $logfiles > /dev/null
	retval=$?
    fi
    set +o pipefail

    for logfile in $vlogfiles; do
	echo "------------------------------------------------------------------------" >> $logfile
	echo "${progname}: RV $retval END $( date +%Y-%m-%d.%H:%M:%S ) veva: $@" >> $logfile
	echo "========================================================================" >> $logfile
    done

    return $retval
}

#
# usage: die <message...>
#
# Generic error condition exit function used as a last resort when a more
# graceful handling of the error is not possible or not yet implemented.
#
# globals used: cleanup_command
#
function die {
    echo -en "\n"
    status "===================================="
    status $@
    status "===================================="
    
    status "VSYS has exited prior to task completion"
    status "===================================="

    ##
    ## clean up
    ##
    status "cleaning up..."
    status "(please wait up to 1 minute if possible)"
    if (($vopt_debug)); then
	status "cleanup_command is $cleanup_command"
    fi
    veva $cleanup_command
    status "done cleaning up...  have a nice day!"

    exit 1
}

#
# usage: die_bug <message...>
#
# Generic error condition exit function used as a last resort when a more
# graceful handling of the error is not possible or not yet implemented.
#
# the _bug version of die is called when a truly unexpected condition 
# warrants developer feedback 
#
# globals used: cleanup_command
#
function die_bug {
    status "===================================="
    status $@
    status "===================================="
    
    status "VSYS has exited ungracefully"
    status ""
    status "please submit a bug report to bugs@viros.org"
    status "===================================="

    ##
    ## clean up
    ##
    status "cleaning up..."
    veva $cleanup_command

    exit 1
}

#
# usage: debug <message...>
#
# wrapper for sending status messages to console and log
#
# globals used: progname, logfiles(not required)
#
function debug {
    time="$( date +%Y-%m-%d.%H:%M:%S )"
    if (($vopt_debug)); then
	echo "${viros_comtrace}: ${time}: debug: $@"
    fi
    for logfile in $logfiles; do
	echo "${progname}: ${time}: debug: $@" >> $logfile
    done
}

#
# usage: debugcat <filename>
#
# wrapper for sending status messages to console and log
#
# globals used: progname, logfiles(not required)
#
function debugcat {
    if [ ! -f $1 ]; then
	die "file $1 can not be debugcat-ed"
    fi

    time="$( date +%Y-%m-%d.%H:%M:%S )"
    if (($vopt_debug)); then
	echo "${viros_comtrace}: ${time}: debug: catting file $1"
	cat $1
    fi
    for logfile in $logfiles; do
	echo "${progname}: ${time}: debug: catting file $1" >> $logfile
	cat $1 >> $logfile
    done
}

#
# usage: verbose <message...>
#
# wrapper for sending status messages to console and log
#
# globals used: progname, logfiles(not required)
#
function verbose {
    time="$( date +%Y-%m-%d.%H:%M:%S )"
    if (($vopt_verbose)); then
	echo "${viros_comtrace}: ${time}: verbose: $@"
    elif (($vopt_debug)); then
	echo "${viros_comtrace}: ${time}: verbose: $@"
    fi
    for logfile in $logfiles; do
	# todo: figure out why this if case is necessary
	# (triggerred a failure when I did a ctrl c on a non --debug run)
	if [ -d "$( dirname $logfile )" ]; then
	    echo "${progname}: ${time}: verbose: $@" >> $logfile
	fi
    done
}

#
# usage: status <message...>
#
# wrapper for sending status messages to console and log
#
# globals used: progname, logfiles(not required)
#
function status {
    bequiet=0
    if [ "x${vopt_quiet}" == "x1" ]; then
	bequiet=1
    elif [ "x${vopt_quiet}" == "x1" ]; then
	bequiet=1
    fi

    time="$( date +%Y-%m-%d.%H:%M:%S )"
    if ((! $bequiet)); then
	echo "${progname}: ${time}: status: $@"
    fi
    for logfile in $logfiles; do
	echo "${progname}: ${time}: status: $@" >> $logfile
    done
}

#
# usage: simple_statuslogger <logfile>
#
# this function passes it's stdin to the logfile, and outputs a . to stdout
# for every line of stdin.
#
function simple_statuslogger {
    wdone=0
    while (( !$wdone )); do
        read
        wdone=$?
        echo "${REPLY}" >> $1
	if (($vopt_debug)); then
	    echo "${REPLY}" 
	else
	    echo -en "."
	fi
    done
    echo -en "\n" >> $1
    echo -en "\n"
}

#
# usage: statuslogger <logfile>
#
# like statuslogger, but designed for the os installer output
# (anaconda.log and other).  In addition, lines of dots are broken either
# when they hit $numdots_perline, or when a timestamp has not been printed
# in more than $minvalsecs
#
function statuslogger {
    logfile=$1
    msg_prefix=$2
    divider=$3

    if [ "x${divider}" == "x" ]; then
	divider=1
    fi

    if [ "x${msg_prefix}" == "x" ]; then
	msg_prefix="progress"
    fi

    if [ "x${logfile}" == "x" ]; then
	logfile=/dev/null
    fi

    minvalsecs=300
    numdots_perline=42
    numdots=0
    wdone=0
    oldepochsecs=$( date +%s )
    divcount=0
    while (( !$wdone )); do
        read
	wdone=$?

	# todo: use a timer, and if the time since the 
	# last divcount reset has been longer than a constant
	# go ahead and jump divcount to divider
	divcount=$(( $divcount + 1 ))

	if [ $divcount -eq $divider ]; then
            divcount=0
	    
            newepochsecs=$( date +%s )
            timediff=$(($newepochsecs - $oldepochsecs))
            if [ $timediff -gt $minvalsecs ]; then
		numdots=0
		echo -en "\n"
		oldepochsecs=$newepochsecs
            fi
	    
            if (( !$numdots )); then
		time="$( date +%H:%M:%S )"
		echo -en "${msg_prefix}: ${time}: "
            fi
            echo "${REPLY}" >> ${logfile}
            echo -en "."
            numdots=$(($numdots + 1))
            if [ $numdots -eq $numdots_perline ]; then
		numdots=0
		echo -en "\n"
            fi
	fi
    done
    echo -en "\n"
}

#
# usage: waitonoutput <filename> <string> <period> <timeout>
#
# waitonoutput watches a particular filename, looking for the given
# string.  waitonouput will check periodically with the period 
# specified in seconds, until a maximum timeout value specified in
# seconds.  If the string is found before the timeout expires, 0 (no error)
# is returned.  Otherwise, 1 (error) will be returned
#
function waitonoutput {
    
    filename="$1"
    string="$2"
    period="$3"
    timeout="$4"

    # local variables
    timeelapsed=0
    
    while [ true ]; do
	if ( grep -q "$string" $filename > /dev/null 2>&1 ); then
	    return 0
	fi

	if (( $timeelapsed > $timeout )); then
	    return 1
	fi
	
	sleep $period
	timeelapsed=$(($timeelapsed + $period))
    done
}

##
## usage: make_vncstartup <output_twmrc_filename>
##
## generates a minimal xstartup for Xvnc suitable for qemu in qrap
##
function make_vncstartup {
    cat <<EOF > $1
#!/bin/bash
#twm &
#xterm &
EOF
    chmod +x $1
}

function install_smirfgen {
    src_dir=${1}
    dest_dir=${2}

    verbose "installing smirfgen..."
    mkdir ${dest_dir}/lib/viros
    mkdir ${dest_dir}/lib/viros/scripts
    mkdir ${dest_dir}/lib/viros/ZyX-Live-OS
    cp ${src_dir}/bin/smirfgen \
	${dest_dir}/bin/smirfgen
    # XXX: expediency, splitter should probably be bashified someday
    if [ -x /bin/splitter ]; then
	cp /bin/splitter \
	    ${dest_dir}/bin/splitter
    elif [ -x /usr/bin/splitter ]; then
	cp /usr/bin/splitter \
	    ${dest_dir}/bin/splitter
    else
	die "no splitter available"
    fi
    
    cp -a ${src_dir}/lib/viros/scripts/* \
	${dest_dir}/lib/viros/scripts/
    cp -a ${src_dir}/lib/viros/ZyX-Live-OS/* \
	${dest_dir}/lib/viros/ZyX-Live-OS/

    verbose "... done"
}


function cleanup_and_exit {
    ##
    ## cleanup and exit
    ##
    if (( $vopt_debug )); then
	verbose "debug enabled: NOT removing tmpdir ${tmpdir}"
    else
	verbose "removing tmpdir, was ${tmpdir}"
	rm -rf "${tmpdir}"
    fi
    verbose "goodbye!"
    exit 0
}

