#!/bin/bash
#
#############################################################################
#
# mutate: a tool for adding traits to Vir(OS/tual) System Images
#
#############################################################################
#
# Copyright 2007-2011 Douglas McClendon <dmc AT filteredperception DOT org>
#
#############################################################################
#
# This file is part of VirOS.
#
#    VirOS is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    VirOS is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with VirOS.  If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################


#############################################################################
##
## VirOS mutate
##
## usage: mutate [options] [[--traits=<traitspec>]] <target.vsi>
##
## mutate modifies the target.vsi according to the specified traits.
## The specified traits are assumed (for now) to either be a directory,
## or a directory in the standard viros traits dir (/usr/lib/viros/traits)
## (or developer environment equivalent)
##
## In addition to the contents of the directory being copied with root
## ownership to the root of the target vsi's /, if a /trait-install
## directory exists, any pre or post programs within it will be executed.
##
## Traits must be prefixed with either 'splice-' or 'unsplice-'.  The 
## latter form can be used to remove traits that were added by an 
## included .vml which for whatever reason you do not want to modify.
##
## traitspec may have options, attached to the directory name with :: and
## seperated with :.  E.g.
##
## --traits=splice-EnableGDMAutoLogin::user=kablui:timeout=30 
##
## These options will be visible to the pre and post scripts a sourceable
## bash script in /trait-expanded/trait-install/trait-options.
##
## multiple traits are applied in order.
##
##
## Many further improvements to this functionality are planned.
##
#############################################################################


#############################################################################
##
## constant definitions
##
viros_prefix=/usr


#############################################################################
##
## load viros system library
##
if [ -f "$( dirname $0 )/libvsys.sh" ]; then
    source "$( dirname $0 )/libvsys.sh"
elif [ -f "${viros_prefix}/lib/viros/scripts/libvsys.sh" ]; then 
    source "${viros_prefix}/lib/viros/scripts/libvsys.sh" 
else
    echo "$0: error: fatal: could not load viros system library libvsys.sh"
    exit 1
fi

#############################################################################
##
## embedded qfakeroot script
##
function target_script_to_run_as_root {

    #
    # target mutation/trait environment assumptions:
    #
    # /input has contents of the trait as traitname.tar,
    # /target is where the target root is mounted
    # /scratch is a mounted workarea with lots of space
    # /target has bindmounts for dev, proc, sys, selinux, and scratch
    #

    export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/input/bin:/input/sbin"

    echo -en "\n"
    echo -en "########################################################################\n"
    echo -en "########################################################################\n"
    echo -en "##                                                                    ##\n"
    echo -en "## status: mutate - fedora/x86 - starting                             ##\n"
    echo -en "##                                                                    ##\n"
    echo -en "\n"


    save_traits=0
    if [ -f /input/mutateopts ]; then
	source /input/mutateopts
    fi

    echo -en "\n"
    echo -en "##\n"
    echo -en "## status: mutate - creating swap\n"
    echo -en "##\n"
    echo -en "\n"

    swapk=$(( $( cat /proc/meminfo  | grep MemTotal | awk '{print $2}' ) * 1 ))
    dd if=/dev/zero of=/scratch/qswap \
	bs=1k count=$(( $swapk )) > /dev/null 2>&1

    mkswap /scratch/qswap
    swapon /scratch/qswap

    # debugging
    #cat /proc/meminfo
    #cat /proc/swaps
    
    echo -en "\n"
    echo -en "##\n"
    echo -en "## status: mutate - initializing selinux\n"
    echo -en "##\n"
    echo -en "\n"

    mkdir /selinux
    mount -t selinuxfs selinuxfs /selinux
    
    echo -en "\n"
    echo -en "##\n"
    echo -en "## status: mutate - initializing networking\n"
    echo -en "##\n"
    echo -en "\n"

    ifconfig eth0 10.0.2.42 broadcast 10.0.2.255 netmask 255.255.255.0
    route add default gw 10.0.2.2

    echo -en "\n"
    echo -en "##\n"
    echo -en "## status: mutate - initializing target disk mountpoints\n"
    echo -en "##\n"
    echo -en "\n"

    mkdir /target
    mount /dev/qfrdi-base-p1 /target

    mkdir /target/mutate.scratch
    mount --bind /scratch /target/mutate.scratch

    # bindmount system directories into the chroot
    mount --bind /dev /target/dev
    mount --bind /dev/pts /target/dev/pts
    mount --bind /selinux /target/selinux
    mount --bind /proc /target/proc
    mount --bind /sys /target/sys

    source /target/etc/selinux/config
    if [ "x${SELINUX}" == "xpermissive" -o "x${SELINUX}" == "xenforcing" ]; then
	chroot /target /usr/sbin/load_policy
	chroot /target /usr/sbin/setenforce permissive
    fi
    
    echo -en "\n"
    echo -en "##\n"
    echo -en "## status: mutate - applying traits\n"
    echo -en "##\n"
    echo -en "\n"

    trait_num=0
    for trait in $( < /input/traitlist ); do
	trait_num=$(( $trait_num + 1 ))

	echo -en "\n"
	echo -en "##\n"
	echo -en "## status: mutate - applying trait number $trait_num : $trait\n"
	echo -en "##\n"
	echo -en "\n"

	if ( grep -q "no_mutate_prepost=1" \
	    /input/options.${trait}.${trait_num} ); then
	    runprepost=0
	else
	    runprepost=1
	fi

	mkdir /target/trait-expanded
	mkdir /target/trait-expanded/trait-install

	# inelegant: base-trait-p* may depend on these
	cp /input/vreplace /target/trait-expanded/trait-install/
	cp /input/vmirmog /target/trait-expanded/trait-install/

	# copy local webserver (e.g. for repo mirrors) configuration in place
	if [ -f /input/webserver.cfg ]; then
	    source /input/webserver.cfg
	    cp /input/webserver.cfg \
		/target/trait-expanded/trait-install/webserver.cfg
	fi
	# if the base provides a mutate pre script, run it
	if [ -x /input/base-trait-pre ]; then
	    if (( $runprepost )); then
		if [ "x${mutate_webserver_ip}" != "x" ]; then
		    wget --quiet -O /target/tmp/mutate.vsys.mirrorlist.cfg \
			http://${mutate_webserver_ip}:${mutate_webserver_port}/mirrors/${mirror_listconfig}
		    if (($?)); then
			echo "ERROR: wget of mirror configuration failed"
		    fi
		fi
		cp /input/base-trait-pre \
		    /target/trait-expanded/trait-install/base-trait-pre
		chroot /target /trait-expanded/trait-install/base-trait-pre
	    fi
	fi

	pushd /target/trait-expanded > /dev/null 2>&1 

	tar xpsf /input/trait.${trait}.${trait_num}.tar
	cp /input/options.${trait}.${trait_num} ./trait-install/trait-options

	# save desired traits
	if (( $save_traits )); then
	    if ( ! echo "${trait}" | grep -q "^nosave-" ); then
		mkdir -p /target/VirOS.prime_rootfs/source/viros-traits
		cp /input/trait.${trait}.${trait_num}.tar \
		    /target/VirOS.prime_rootfs/source/viros-traits/
		cp /input/options.${trait}.${trait_num} \
		    /target/VirOS.prime_rootfs/source/viros-traits/
	    fi
	fi

	if [ -x /target/trait-expanded/trait-install/pre ]; then

	    echo -en "\n"
	    echo -en "##\n"
	    echo -en "## status: mutate - running trait pre script for $trait_num : $trait\n" 
	    echo -en "##\n"
	    echo -en "\n"

	    chroot /target /trait-expanded/trait-install/pre
	fi

	chroot /target chown -R root:root /trait-expanded

	pushd /target/trait-expanded > /dev/null 2>&1
	tar -cpsf - . | \
	    ( cd /target ; tar xpsf - )
	rm -rf /target/trait-install
	popd > /dev/null 2>&1

	if [ -x /target/trait-expanded/trait-install/post ]; then
	    echo -en "\n"
	    echo -en "##\n"
	    echo -en "## status: mutate - running trait post script for $trait_num : $trait\n" 
	    echo -en "##\n"
	    echo -en "\n"

	    chroot /target /trait-expanded/trait-install/post
	fi

	popd > /dev/null 2>&1

	# if the base provides a mutate post script, run it
	if [ -x /input/base-trait-post ]; then
	    if (( $runprepost )); then
		cp /input/base-trait-post \
		    /target/trait-expanded/trait-install/base-trait-post
		chroot /target /trait-expanded/trait-install/base-trait-post
	    fi
	fi

	rm -rf /target/trait-expanded

    done

    # unbindmount system directories into the chroot
    umount /target/sys
    umount /target/proc
    umount /target/selinux
    umount /target/dev/pts
    umount /target/dev

    echo -en "\n"
    echo -en "##\n"
    echo -en "## status: mutate - disabling swap\n" 
    echo -en "##\n"
    echo -en "\n"

    swapoff /scratch/qswap
    rm -f /scratch/qswap

    umount /target/mutate.scratch
    rmdir /target/mutate.scratch

    umount /target
    rmdir /target

    echo -en "\n"
    echo -en "##                                                                    ##\n"
    echo -en "## status: mutate - fedora/x86 - complete                             ##\n"
    echo -en "##                                                                    ##\n"
    echo -en "########################################################################\n"
    echo -en "########################################################################\n"
    echo -en "\n"

}
# run the qfakeroot special function and exit, if being called as such
if [ "$progname" == "qfakeroot.command" ]; then
    target_script_to_run_as_root
    exit 0
fi
##
## end embedded qfakeroot script
##
#############################################################################


#############################################################################
#############################################################################
##
## functions
##
#############################################################################
#############################################################################


#############################################################################
##
## override libvopt.sh usage function
##
function usage {
    echo ""
    echo "${progname} \\"
    echo "    [--help] \\"
    echo "    [--quiet] \\"
    echo "    [--verbose] \\"
    echo "    [--debug] \\"
    echo "    [--mirrorlist=</path/to/vsys.mirrorlist.cfg>] \\"
    echo "    [[--traits=<traitspec>]] \\"
    echo "    <target.vsi>"
    echo ""

    if [ "x${1}" == "xclean" ]; then
	exit 0
    else 
	exit 1
    fi
}


#############################################################################
#############################################################################
##
## main
##
#############################################################################
#############################################################################


#############################################################################
##
## use TMPDIR environment if set
##
if [ "x${TMPDIR}" == "x" ]; then
    default_vopt_tmpdir="/tmp"
else
    default_vopt_tmpdir="${TMPDIR}"
fi


#############################################################################
##
## define and parse options
##
export LIBVOPT_IGNORE_UNKNOWN_OPTIONS=true
vregopt help boolean 0
# todo: inherit this?(consider)
#       2k11/01/06 code perusal - inheriting here seems necessary in the
#       generate case, not sure how it seems to be working on my current build
vregopt config string ""
vregopt verbose boolean 0 inherit
vregopt debug boolean 0 inherit
vregopt quiet boolean 0 inherit
vregopt mirrorlist string "${HOME}/.viros/mirrors.link/el6/viros.mirrors.cfg" inherit
vregopt mutateopts cumulative "" inherit
vregopt traits cumulative "" inherit
# sigh, trait_dirs has to be special like add_search_paths
# todo: document the vile libvopt system much better
#vregopt trait_dirs cumulative "" inherit
vregopt tmpdir string "${default_vopt_tmpdir}" inherit
vparseopt "$@"

if (( $vopt_help )); then 
    usage clean 
fi

debug "in mutate ml is ${vopt_mirrorlist}"


#############################################################################
##
## initialization
##
verbose "creating temporary directory..."
export TMPDIR=${vopt_tmpdir}
tmpdir=$( mktemp -t -d vtmp.${progname}.${starttime}.${mypid}.XXXXXXXXXX )
if (($?)); then
    die "failed to mktemp"
fi
export TMPDIR=${tmpdir}
verbose "temporary directory is ${tmpdir}"

export vopt_debug
export vopt_verbose
export vopt_quiet

touch ${tmpdir}/qfakeroot.config


#############################################################################
##
## process command line arguments
##

debug "vopts_numargs is $vopts_numargs ${vopts_args[1]} xxx ${vopts_args[2]} yyy"

if [ $vopts_numargs -ne 1 ]; then usage; fi

target=$( normalize_path "${vopts_args[1]}" )

if [ ! -f "${target}" -a ! -b "${target}" ]; then
    die "error: could not find target system image: ${target}"
fi

num_traits=0

splitter "$vopt_traits" | \
    grep -v "^\s*$" > $tmpdir/traitlistnopts
while read line; do
    # splice and unspice traits into the final trait list 
    if ( echo $line | grep -q "^splice-" ); then
	splice_trait=$( echo $line | sed -e 's/^splice-//' )
	num_traits=$(( $num_traits + 1 ))
	traits[$num_traits]=$splice_trait
    elif ( echo $line | grep -q "^unsplice-" ); then
	# search through list, if find a match, start condensing list and then decrement numtraits
	unsplice_trait=$( echo $line | sed -e 's/^unsplice-//' )
	shrinkit=0

	for (( i=1 ; $i <= ${num_traits} ; i=$(( $i + 1 )) )); do
	    if ((${shrinkit})); then
		# on all but the last one, set to the next higher value
		if [ $i -ne ${num_traits} ]; then
		    traits[$i]=${traits[$((i + 1))]}
		fi
	    else
		if [ "${traits[$i]}" == "${unsplice_trait}" ]; then
		    # found the trait to unsplice
		    shrinkit=1
		    traits[$i]=${traits[$((i + 1))]}
		fi
	    fi
	done
	# now shrink the actual number
	if ((${shrinkit})); then
	    num_traits=$(( $num_traits - 1 ))
	fi
    else
	die "error: trait must be either splice- or unsplice-, was $line"
    fi
done < $tmpdir/traitlistnopts

if (($viros_devenv)); then
    vopt_trait_dirs=". ${vopt_trait_dirs} ${viros_devdir}/traits"
else
    vopt_trait_dirs=". ${vopt_trait_dirs} ${viros_prefix}/lib/viros/traits"
fi

for (( i=1 ; $i <= ${num_traits} ; i=$(( $i + 1 )) )); do
    trait=${traits[$i]}

    ##
    ## prepare target trait payload
    ##

    trait_base="$( echo "$trait" | sed -e 's/\:\:.*//' )"
    trait_opts="$( echo "$trait" | sed -e "s/^${trait_base}//" )"

    echo ${trait_base} >> ${tmpdir}/traitlist

    # iterate over trait directories to find the first that has the target trait
    trait_dir=""
    
    for test_trait_dir in $vopt_trait_dirs; do
	if [ -d "${test_trait_dir}/${trait_base}" ]; then
	    trait_dir=$( normalize_path "${test_trait_dir}/${trait_base}" )
	    break
	fi
    done
    if [ "${trait_dir}" == "" ]; then
	die "could not find trait ${trait_base}"
    fi

    # append trait's qfakeroot.config onto the cumulative qfakeroot.config
    if [ -f ${trait_dir}/trait-install/qfakeroot.config ]; then
	cat ${trait_dir}/trait-install/qfakeroot.config \
	    >> ${tmpdir}/qfakeroot.config
    fi

    pushd ${trait_dir} > /dev/null 2>&1
    tar cf ${tmpdir}/trait.${trait_base}.${i}.tar .
    popd > /dev/null 2>&1

    echo "add_nonvsi_files ${tmpdir}/trait.${trait_base}.${i}.tar:/input/trait.${trait_base}.${i}.tar" >> ${tmpdir}/qfakeroot.config

    ( eval echo '${trait_opts}' ) | sed -e 's/:/\n/g' > ${tmpdir}/options.${trait_base}.${i}

    echo "add_nonvsi_files ${tmpdir}/options.${trait_base}.${i}:/input/options.${trait_base}.${i}" >> ${tmpdir}/qfakeroot.config
    
done

if ((! $num_traits)); then
    status "no traits specified to be added"
    usage
fi

##
## pass specified vmut options as a file
##
echo -en ${vopt_mutateopts} > ${tmpdir}/mutateopts

##
## handle mirrorlist option
##

if [ "x${vopt_mirrorlist}" != "x" ]; then
    mirror_docroot=$( dirname $( normalize_path ${vopt_mirrorlist} ) )
    mirror_listconfig=$( basename ${vopt_mirrorlist} )
    if [ ! -f "${vopt_mirrorlist}" ]; then
	mkdir -p "$( dirname ${vopt_mirrorlist} )"
	touch "${vopt_mirrorlist}" 
    fi

    vsys_mutate_httpdport=$( findfreeport \
	$viros_arap_portmin $viros_arap_portmax )
    retval=$?
    if (($retval)); then
	die "could not find available port for private httpd server"
    fi

    status "vsys_mutate_httpdport is $vsys_mutate_httpdport"

    echo "mutate_webserver_ip=10.0.2.2" > ${tmpdir}/webserver.cfg
    echo "mutate_webserver_port=${vsys_mutate_httpdport}" \
	>> ${tmpdir}/webserver.cfg
    echo "mirror_listconfig=${mirror_listconfig}" \
	>> ${tmpdir}/webserver.cfg

    echo "add_nonvsi_files ${tmpdir}/webserver.cfg:/input/webserver.cfg" \
	>> ${tmpdir}/qfakeroot.config

    status "starting dedicated webserver"

    mkdir -p ${tmpdir}/webserver
    mkdir -p ${tmpdir}/webserver_docroot
    ln -s ${mirror_docroot} ${tmpdir}/webserver_docroot/mirrors
    veva webserver \
	--port=${vsys_mutate_httpdport} \
	--docroot=${tmpdir}/webserver_docroot \
	--confdir=${tmpdir}/webserver \
	start
    
    cleanup_command="${cleanup_command} ; \
	status \"stopping mutate private http server...\" ; \
	veva webserver \
	--port=${vsys_mutate_httpdport} \
	--docroot=${mirror_docroot} \
	--confdir=${tmpdir}/webserver \
	stop \
	"
fi

##
## get distro and arch of target
##

get_dna_of_vsi ${target} ${tmpdir}/vsidna
. ${tmpdir}/vsidna

##
## prepare base-specific trait pre/post install programs
##

if (($viros_devenv)); then
    mutatedir="${viros_devdir}/ancestors/${distro}/${arch}/mutate"
else
    mutatedir="/usr/lib/viros/ancestors/${distro}/${arch}/mutate"
fi

verbose "mutatedir is ${mutatedir}"

if [ -x ${mutatedir}/pre ]; then
    verbose "adding base-trait-pre to qfakeroot.config"
    echo "add_nonvsi_files ${mutatedir}/pre:/input/base-trait-pre:755" \
	>> ${tmpdir}/qfakeroot.config
else
    verbose "NOT adding base-trait-pre to qfakeroot.config"
fi

if [ -x ${mutatedir}/post ]; then
    echo "add_nonvsi_files ${mutatedir}/post:/input/base-trait-post:755" \
	>> ${tmpdir}/qfakeroot.config
fi


##
## major processing
##

touch ${tmpdir}/qfr.log

qfakeroot \
    --guest_smirf \
    --command="${progdir}/${progname}" \
    --qflags="-m ${viros_mutate_qmem}" \
    --scratch=20G \
    --add_modules="ne2k_pci 8139cp 8139too" \
    --add_files="/bin/bash" \
    --add_files="bindir:/usr/bin:755" \
    --add_files="bindir:/usr/sbin:755" \
    --add_nonvsi_files="${viros_scripts_dir}/libvsys.sh:${viros_prefix}/lib/viros/scripts/libvsys.sh" \
    --add_nonvsi_files="${viros_scripts_dir}/vdefs:${viros_prefix}/lib/viros/scripts/vdefs" \
    --add_nonvsi_files="${viros_scripts_dir}/libvopt.sh:${viros_prefix}/lib/viros/scripts/libvopt.sh" \
    --add_nonvsi_files="${viros_scripts_dir}/functions:${viros_prefix}/lib/viros/scripts/functions" \
    --add_nonvsi_files="${viros_scripts_dir}/vcommon:${viros_prefix}/lib/viros/scripts/vcommon" \
    --add_nonvsi_files="${viros_scripts_dir}/smirfgen:${viros_prefix}/bin/smirfgen" \
    --add_nonvsi_files="$( which splitter ):/bin/splitter" \
    --add_nonvsi_files="${viros_scripts_dir}/vreplace:/input/vreplace" \
    --add_nonvsi_files="${viros_scripts_dir}/vmirmog:/input/vmirmog" \
    --add_files="/bin/date" \
    --add_files="/bin/mount" \
    --add_files="/bin/umount" \
    --add_files="/bin/basename" \
    --add_files="/usr/bin/dirname" \
    --add_files="/sbin/mkswap" \
    --add_files="/usr/bin/awk" \
    --add_files="/sbin/swapon" \
    --add_files="/sbin/swapoff" \
    --add_files="/bin/cp" \
    --add_files="/bin/mkdir" \
    --add_files="/bin/tar" \
    --add_files="/bin/cat" \
    --add_files="/bin/zcat" \
    --add_files="/bin/rm" \
    --add_files="/bin/sh" \
    --add_files="/bin/chown" \
    --add_files="/usr/bin/which" \
    --add_files="/usr/bin/tee" \
    --add_files="/usr/sbin/chroot" \
    --add_files="/usr/bin/find" \
    --add_files="/bin/ping" \
    --add_files="/bin/ps" \
    --add_files="/sbin/fuser" \
    --add_files="/usr/bin/wget" \
    --add_nonvsi_files="${tmpdir}/mutateopts:/input/mutateopts" \
    --add_nonvsi_files="${tmpdir}/traitlist:/input/traitlist" \
    --config="${tmpdir}/qfakeroot.config" \
    --disk_image="${target}" \
    --outputdir=${tmpdir}/qfakeroot.outputdir \
    --debug --verbose \
    > ${tmpdir}/qfr.log 2>&1 &
qfrpid=$!
echo "$qfrpid" > ${tmpdir}/qfr.pid

cleanup_command="${cleanup_command} ; \
    status \"status: terminating qfr...\" ; \
    kill ${qfrpid} ; sleep 3 ; kill -KILL ${qfrpid} \
    "

if (($vopt_debug)); then
    tail -f --lines=9999 --pid=$qfrpid ${tmpdir}/qfr.log | \
	tee -a ${tmpdir}/debug.log
else
    tail -f --lines=9999 --pid=$qfrpid ${tmpdir}/qfr.log | \
	statuslogger \
	${tmpdir}/debug.log \
	"mutate progress" \
	${viros_mutate_statuslogger_divfactor}
fi


##
## clean up and exit
##

if (($vopt_debug)); then
    debug "NOT REMOVING tmpdir ${tmpdir}"
else
    verbose "cleaning up tmpdir ${tmpdir}"
    rm -rf ${tmpdir}
fi

veva $cleanup_command

status "done"

exit 0

