#!/bin/bash
#
#############################################################################
#
# synthesize: a tool to synthesize livecds and other os system images
#
#############################################################################
#
# Copyright 2007-2010 Douglas McClendon <dmc AT filteredperception DOT org>
#
#############################################################################
#
# This file is part of VirOS.
#
#    VirOS is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    VirOS is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with VirOS.  If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################

#
##
##
## VirOS synthesize
##
## usage: vsys [options] synthesize [options]
##
## for detailed usage information: vsys help synthesize
##


##
## constant definitions
##
viros_prefix=/usr

##
## load viros system library
##
if [ -f "$( dirname $0 )/libvsys.sh" ]; then
    source "$( dirname $0 )/libvsys.sh"
elif [ -f "${viros_prefix}/lib/viros/scripts/libvsys.sh" ]; then 
    source "${viros_prefix}/lib/viros/scripts/libvsys.sh" 
else
    echo "$0: error: fatal: could not load viros system library libvsys.sh"
    exit 1
fi

##
## functions
##

##
## override libvopt.sh usage function
##
function usage {
    echo ""
    echo "${progname} \\"
    echo "    [--help] [--quiet] [--verbose] [--debug] \\"
    echo "    --strain=<strain> | --config=<config> \\ ### default: fz8"
    echo "    [[--traits=<traitspec>]] \\"
    echo "    [[--vxmogopts=<transmogrifier options>]] \\"
    echo "    [--transmogrifier=<transmogrifier>] \\   ### default: zyx-live"
    echo "    [--output=<filename>]                    ### default: ./vsys.iso"
    echo ""

    if [ "x${1}" == "xclean" ]; then
	exit 0
    else 
	exit 1
    fi
}

function cleanup_and_exit {
    ##
    ## cleanup and exit
    ##
    if (( $vopt_debug )); then
	verbose "debug enabled: NOT removing tmpdir ${tmpdir}"
    else
	verbose "removing tmpdir, was ${tmpdir}"
	rm -rf ${tmpdir}
    fi
    verbose "goodbye!"
    exit 0
}


##
## use TMPDIR environment if set
##

if [ "x${TMPDIR}" == "x" ]; then
    default_vopt_tmpdir="/tmp"
else
    default_vopt_tmpdir="${TMPDIR}"
fi


##
## define and parse options
##

#
# general vsys options
#
export LIBVOPT_IGNORE_UNKNOWN_OPTIONS=true
vregopt config string ""
vregopt help boolean 0
vregopt verbose boolean 0 inherit
vregopt debug boolean 0 inherit
vregopt quiet boolean 0 inherit
vregopt cachedir string "" inherit
vregopt tmpdir string "${default_vopt_tmpdir}" inherit

# this is the size of the qemu vsi rootfs
vregopt vsysgen_output_container_size \
    string "${v_x_def__output_container_size}" inherit
vregopt vsysgen_distro \
    string "${v_x_def__distro}" inherit
vregopt vsysgen_arch \
    string "${v_x_def__arch}" inherit
vregopt vsysgen_install_boot_iso \
    string "${v_x_def__install_boot_iso}" inherit
vregopt vsysgen_install_boot_iso_sha256sum \
    string "${v_x_def__install_boot_iso_sha256sum}" inherit
vregopt vsysgen_distro_config \
    string "${v_x_def__distro_config}" inherit
vregopt vsysgen_boot_cmdline \
    string "${v_x_def__boot_cmdline}" inherit

vregopt vsysgen_screencast_output string "" inherit

vregopt output string "./viros.vsi"
vregopt mirrorlist string "" inherit

# parse options
vparseopt "$@"

if (( $vopt_help )); then 
    usage clean 
fi

# convert any relative paths in output filename
outputfile=$( normalize_path "${vopt_output}" )

# TODO: verify configfile syntax and values (BETTER)

if [ -f "${vopt_vsysgen_distro_config}" ]; then
    vsysgen_distro_configfile=$( normalize_path "${vopt_vsysgen_distro_config}" )
else
    vsysgen_distro_configfile=$( vfindfile ${vopt_vsysgen_distro_config} "ks cfg" ". ${LIBVOPT_CONFIGS_PATHS} ${vopt_add_search_paths}" )
fi

debug "vsysgen_distro_configfile is ${vsysgen_distro_configfile}"

##
## END: ingest config
##

if [ -f "$outputfile" ]; then
    die "${progname}: error: output file $outputfile already exists"
fi

# TODO: check that outputfile is writable, and has sufficient filesystem space

##
## begin processing
##

verbose "initializing..."

##
## create temp directory
##

verbose "creating temporary directory..."
export TMPDIR=${vopt_tmpdir}
tmpdir=$( mktemp -t -d vtmp.${progname}.${starttime}.${mypid}.XXXXXXXXXX )
if (($?)); then
    die "failed to mktemp"
fi
export TMPDIR=${tmpdir}
verbose "temporary directory is ${tmpdir}"

if [ "x${vopt_cachedir}" == "x" ]; then
    mkdir ${tmpdir}/cachedir
    vopt_cachedir="${tmpdir}/cachedir"
fi

# ugh (there must be a less ugly way to get ~/.viros/cachedir to work here)
vopt_cachedir=$( eval echo "${vopt_cachedir}" )
veva mkdir -p "${vopt_cachedir}"

export vopt_debug
export vopt_verbose
export vopt_quiet

intlogfile="${tmpdir}/vsys.log"

vhttpdroot="${tmpdir}/vsys_docroot"


# mainly this is for qrap callback assumption
# TODO: change this, make it so callback takes an arg of its initial dir
cd $tmpdir

# create intlogfile
veva touch $intlogfile
logfiles="$intlogfile"

verbose "preparing synthesis materials..."

## get boot iso
boot_iso_basename=$( basename ${vopt_vsysgen_install_boot_iso} )

if [ ! -f "${vopt_cachedir}/${boot_iso_basename}" ]; then
#    pushd "${vopt_cachedir}" > /dev/null 2>&1
    pushd "${vopt_cachedir}" 
    veva urlgrabber "${vopt_vsysgen_install_boot_iso}"
    popd > /dev/null 2>&1
fi

boot_iso_sha256sum=$( sha256sum "${vopt_cachedir}/${boot_iso_basename}" | sed -e 's/\s.*//' )
if [ "$boot_iso_sha256sum" != "${vopt_vsysgen_install_boot_iso_sha256sum}" ]; then
    die "install boot iso image ${vopt_cachedir}/${boot_iso_basename} has the wrong sha256sum $boot_iso_sha256sum which does not match the expected ${vopt_vsysgen_install_boot_iso_sha256sum} .  Please try removing this file so that it is downloaded again"
fi

##
## prepare a local copy of runpre/post for target.  qrap callback
## will edit and package later
##
#note: more frontend implicit selection
veva cp -a \
    ${viros_ancestors_dir}/${vopt_vsysgen_distro}/${vopt_vsysgen_arch}/vinsts/qrap/runpre \
    ${tmpdir}/runpre

#note: more frontend implicit selection
veva cp -a \
    ${viros_ancestors_dir}/${vopt_vsysgen_distro}/${vopt_vsysgen_arch}/vinsts/qrap/runpost \
    ${tmpdir}/runpost

# prepare docroot for private webserver
mkdir -p ${vhttpdroot}

# future refactoring note: this code started as a copy of similar from mutate
if [ "x${vopt_mirrorlist}" != "x" ]; then
    if [ ! -f "${vopt_mirrorlist}" ]; then
        die "specified mirrorlist ${mirrorlist} is not a file"
    else
        mirror_docroot=$( dirname $( normalize_path ${vopt_mirrorlist} ) )
        mirror_listconfig=$( basename ${vopt_mirrorlist} )
    fi
    ln -s ${mirror_docroot} ${vhttpdroot}/mirrors
    # todo: should also run vmirmog on kickstart
fi

####
#### BEGIN VSYS INSTALL
####

status "creating target system image"

debug "creating build copy of OS installation configuration"
ksflatten --output=${tmpdir}/uos.cfg ${vsysgen_distro_configfile} 
veva cp -a \
    ${viros_ancestors_dir}/${vopt_vsysgen_distro}/${vopt_vsysgen_arch}/vinsts/qrap/kswrap.cfg \
    ${tmpdir}/kswrap.cfg
pushd ${tmpdir} > /dev/null 2>&1
user_req_rootfs_size=$( cat uos.cfg | \
    grep "^part" | \
    sed -e 's/.*\-\-size\=\([^\s]*\)\s.*/\1/' )
user_req_rootfs_bytes_per_inode=$( cat uos.cfg | \
    grep "^part" | \
    sed -e 's/.*\-\-bytes\-per\-inode\=\([^\s]*\)\s.*/\1/' )
cat uos.cfg \
    | grep -v "^part" \
    > uos.stripped.cfg
sed -i -e 's/VKICKSTARTFILE/uos\.stripped\.cfg/' kswrap.cfg

# note: ksflatten for f11 has bug mentioned on fedora-livecd-list
#ksflatten --output=os.cfg ./kswrap.cfg
echo -en "\n\ntext\n\n" > os.cfg
cat uos.stripped.cfg >> os.cfg
cat kswrap.cfg | grep -v "uos.stripped.cfg" >> os.cfg
# end workaround

# pykickstart bug needs to be filed
sed -i os.cfg -e 's/shutdown/poweroff/'

# for live generation, no root password
if ( ! grep -q "^rootpw" os.cfg ); then
    cat <<EOF >> os.cfg
rootpw livefreeordie
%post
passwd -d root
%end
EOF
fi

popd > /dev/null 2>&1

if ( ! grep -q "^install" os.cfg ); then
    cat os.cfg | grep "^repo" > os.repos.cfg
    cat os.cfg | grep -v "^repo" > os.norepos.cfg
    numrepos=$( cat os.repos.cfg | wc -l )
    numrepos_minus_one=$(( $numrepos - 1 ))
    # todo: basearch should be replaced even outside this if clause, but
    # I need to make sure I only do it for repo lines
    cat os.repos.cfg | tail -${numrepos_minus_one} | sed -e 's/\$basearch/i386/' > os.extrarepos.cfg
    cat os.repos.cfg | head -1 > os.instrepo.cfg
    if ( grep -q mirrorlist os.instrepo.cfg ); then
	# todo: don't assume basearch
	mirrorlisturl=$( cat os.instrepo.cfg | \
	    sed -e 's/.*\-\-mirrorlist=//' | \
	    sed -e 's/\$basearch/i386/' )
	echo "mirrorlisturl is ${mirrorlisturl}"
	wget -O mirrorlist.txt "${mirrorlisturl}"
	cat mirrorlist.txt | grep -v "^#" > mirrors.txt
	nummirrors=$( cat mirrors.txt | wc -l )
	echo "nummirrors is xxx $nummirrors xxx"
	mnum=$(( ( $RANDOM % $nummirrors ) + 1 ))
	mchoice=$( cat mirrors.txt | head -${mnum} | tail -1 )
    else
	mchoice=$( cat os.instrepo.cfg | \
	    sed -e 's/.*\-\-baseurl=//' | \
	    sed -e 's/\$basearch/i386/' )
    fi
    cat <<EOF > os.cfg
install
url --url=${mchoice}
EOF
    cat os.extrarepos.cfg >> os.cfg
    cat os.norepos.cfg >> os.cfg
fi
veva cp ${tmpdir}/os.cfg  ${vhttpdroot}/os.cfg

# note: -f qcow2 might be worth trying here after the f12 'feature' 
#       of tolerable qcow2 performance is available
veva qemu-img \
    create \
    ${tmpdir}/outimage.vsi \
    ${vopt_vsysgen_output_container_size}

# inelegant: the following is very fedora specific

# extract kernel and initrd
isoinfo -R -x /isolinux/isolinux.cfg \
    -i ${vopt_cachedir}/${boot_iso_basename} \
    > ${tmpdir}/inst.bootloaderconfig

isoinfo -R -x /isolinux/vmlinuz \
    -i ${vopt_cachedir}/${boot_iso_basename} \
    > ${tmpdir}/inst.kernel

isoinfo -R -x /isolinux/initrd.img \
    -i ${vopt_cachedir}/${boot_iso_basename} \
    > ${tmpdir}/inst.initrd


##
## synthesize callback script to tweak vrun with info about http port and stuff
##
cat <<EOF>>${tmpdir}/synthesize.callback.sh
#!/bin/bash
#
# the pwd here should be the vsys synthesize main tmpdir
#
# the following environment variables should exist:
#        QRAP_HOST_IP
#        QRAP_HTTPD_PORT
#        QRAP_HTTPD_DOCROOT
#        QRAP_VDISPLAY
#
#
# 1) 

vreplace \
    QRAP_HOST_IP "\${QRAP_HOST_IP}" \
    -- ./runpre/runpre

tar cvzf runpre.tgz runpre

tar cvzf ./runpost.tgz runpost

cp -av ./runpre.tgz ./runpost.tgz \${QRAP_HTTPD_DOCROOT}/

vreplace \
    QRAP_HTTPD_PORT "\${QRAP_HTTPD_PORT}" \
    QRAP_HOST_IP "\${QRAP_HOST_IP}" \
    -- \${QRAP_HTTPD_DOCROOT}/os.cfg

# totally untested code
if [ -f \${QRAP_HTTPD_DOCROOT}/mirrors/${mirror_listconfig} ]; then
    vmirmog \
        \${QRAP_HTTPD_DOCROOT}/mirrors/${mirror_listconfig} \
        \${QRAP_HTTPD_DOCROOT}/os.cfg \
        http://\${QRAP_HOST_IP}:\${QRAP_HTTPD_PORT}/mirrors
fi

EOF
chmod +x ${tmpdir}/synthesize.callback.sh

status "launching system installer..."

touch ${tmpdir}/vsys.build.log
vsys qrap \
    --reaper=X \
    --vdisplay=X \
    --vhttpdport=X \
    --vhttpdroot=${vhttpdroot} \
    --recvideo=${tmpdir}/screencast \
    --callback=${tmpdir}/synthesize.callback.sh \
    -m ${viros_synthesize_qmem} -no-reboot -full-screen \
    -boot c -cdrom ${vopt_cachedir}/${boot_iso_basename} \
    -kernel ${tmpdir}/inst.kernel \
    -initrd ${tmpdir}/inst.initrd \
    -append "${vopt_vsysgen_boot_cmdline}" \
    -drive file=${tmpdir}/outimage.vsi,index=0,media=disk,cache=${viros_qemu_cache_type} \
    > ${tmpdir}/vsys.build.log 2>&1 &

vsysgen_qrap_pid=$!

echo "$vsysgen_qrap_pid" > ${tmpdir}/vsys.build.pid.qrap

cleanup_command="${cleanup_command} ; \
    status \"status: terminating qrap...\" ; \
    kill ${vsysgen_qrap_pid} ; sleep 3 ; kill -KILL ${vsysgen_qrap_pid} \
    "

# note: a bug exists seeing spewage from this after ctrl-c and cleanup.
#       this is because qrap for some reason isn't shutting down (why?)

if (($vopt_debug)); then
    tail -f --lines=9999 --pid=$vsysgen_qrap_pid ${tmpdir}/vsys.build.log | \
	tee -a ${tmpdir}/debug.log
else
    tail -f --lines=9999 --pid=$vsysgen_qrap_pid ${tmpdir}/vsys.build.log | \
	statuslogger ${tmpdir}/debug.log "synthesis progress" 1
fi

mv ${tmpdir}/outimage.vsi ${outputfile}

if [ "x${vsysgen_screencast_output}" != "x" ]; then
    veva mv ${tmpdir}/screencast.swf \
	${vsysgen_screencast_output}.swf
    veva mv ${tmpdir}/screencast.html \
	${vsysgen_screencast_output}.html
fi

verbose "processing done, cleaning up at $( date )"

veva $cleanup_command

cleanup_and_exit

status "finished"

exit 0

