#!/bin/bash

##
## set default values for undefined globals that are used
##
if [ "x${viros_comtrace}" = "x" ]; then
    viros_comtrace="${progname}"
else
    viros_comtrace="${viros_comtrace}:${progname}"
fi

##
## set traps
##
trap "die viros ${progname} killed" SIGTERM
trap "die viros ${progname} interrupted by user" SIGINT

