#!/bin/bash
#
#############################################################################
#
# viros: command frontend for the VirOS System Imaging Toolset
#
#############################################################################
#
# Copyright 2007-2009 Douglas McClendon <dmc AT filteredperception DOT org>
#
#############################################################################
#
# This file is part of VirOS.
#
#    VirOS is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    VirOS is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with VirOS.  If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################

#
# viros
#
# usage: viros [options...] <command> [command options...]
#
# viros is a tool to create system images virtually.  Instead of installing
# an operating system to an actual disk on an actual computer, viros allows 
# you to install and configure an operating system within a virtual host.  
# These system images can then be installed onto one or more real local 
# hosts, real remote host elsewhere on the lan or internet, or converted 
# into livecd/dvd iso images.  The emphasis is on reproducably scripting
# installations, so that they can be carried out automatically with no
# user intervention.  Pre-existing recipes can be used, modified, and shared.
#
# Partial Command List:
#
# * help *
# viros help
#
#   - displays usage information, and full command list
#

##
## constant definitions
##
viros_prefix=/usr

##
## load viros system library
##

# note, vsys uses readlink here, because it is the one
# viros script that supports being a symlink outside
# of the viros scripts directory
if [ -f "$( dirname $( readlink -e $0 ) )/libvsys.sh" ]; then
    source "$( dirname $( readlink -e $0 ) )/libvsys.sh"
elif [ -f "${viros_prefix}/lib/viros/scripts/libvsys.sh" ]; then 
    source "${viros_prefix}/lib/viros/scripts/libvsys.sh" 
else
    echo "$0: error: fatal: could not load viros system library libvsys.sh"
    exit 1
fi

##
## override libvopt.sh usage function
##
function usage {
    echo ""
    echo "${progname} \\"
    echo "    [--help] [--quiet] [--verbose] [--debug] \\"
    echo "    [--config=<config>] \\"
    echo "    <viros-command> \\"
    echo "    [[<viros-command-options>]] "
    echo ""

    if [ "x${1}" == "xclean" ]; then
	exit 0
    else 
	exit 1
    fi
}

function cleanup_and_exit {
    ##
    ## cleanup and exit
    ##
    if (( $vopt_debug )); then
	verbose "debug enabled: NOT removing tmpdir ${tmpdir}"
    else
	verbose "removing tmpdir, was ${tmpdir}"
	rm -rf ${tmpdir}
    fi
    verbose "goodbye!"
    exit 0
}


##
## set vsys environment based on development or normal installation detection
##
if [ -f ${progdir}/../../info/AUTHORS ]; then

    pushd ${progdir}/../.. > /dev/null 2>&1
    instdir=$( pwd )
    popd > /dev/null 2>&1

    export viros_scripts_dir="${instdir}/tools/scripts"
else
    export viros_scripts_dir="${progdir}"
fi


##
## sanity check arguments
##

if [ $# -lt 1 ]; then usage; fi

vcommand="$1"

# check to see if exact valid command was specified, otherwise check to see
# if it is an unambiguous abbreviation
if [ ! -x "${viros_scripts_dir}/${vcommand}" ]; then
    scriptname=$( find ${viros_scripts_dir} -name "${vcommand}*" -print | grep -v "~$" )
else
    scriptname="${viros_scripts_dir}/${vcommand}" 
fi

if [ ! -x "$scriptname" ]; then
    status ""
    status "viros: '${vcommand}' is not a valid viros command or unambiguous abbreviation"
    status ""
    status "type 'viros help' for a list of valid commands and more information"
    status ""
    exit 1
fi

shift

# note, added quotes at some point, need to review implications
exec ${scriptname} "$@"

# should not reach here
die "problem executing command '${scriptname}'"

