#!/bin/bash
#
#############################################################################
#
# runpre: script that is run by VirOS mutate after trait injection
#
#############################################################################
#
# Copyright 2007-2010 Douglas McClendon <dmc AT filteredperception DOT org>
#
#############################################################################
#
# This file is part of VirOS.
#
#    VirOS is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    VirOS is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with VirOS.  If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################

echo -en "\n"
echo -en "########################################################################\n"
echo -en "########################################################################\n"
echo -en "##                                                                    ##\n"
echo -en "## status: mutate pre - fedora/x86 - starting                         ##\n"
echo -en "##                                                                    ##\n"
echo -en "\n"

if [ -f /trait-expanded/trait-install/webserver.cfg ]; then
    source /trait-expanded/trait-install/webserver.cfg
else
    exit 0
fi


reposdir=$( cat /etc/yum.conf  | grep "^reposdir=" | sed -e 's/^reposdir=//' )
if [ "${reposdir}" == "" ]; then reposdir=/etc/yum.repos.d; fi

# keep a pristine copy of repos in .unmutated to be restored later
mv ${reposdir} /etc/yum.reposdir.unmutated
cp -a /etc/yum.reposdir.unmutated ${reposdir}


#
# replace $releasever and $basearch in .repo files
#

# alternately the version from generic-release would be better 
# (or really, whatever provides whatever generic-release provides)
replace_rv=$( rpm -q filesystem | sed -e 's/^.*\.fc\([^\.]*\)\.[^\.]*$/\1/' )

# this feels a bit wrong, but I suppose the vm running mutate needs to be
# the same platform as the build target
replace_ba="$( uname -i )"

find \
    ${reposdir} \
    -type f \
    -name "*.repo" \
    -exec sed -i -e "s/\$releasever/${replace_rv}/g"  -e "s/\$basearch/${replace_ba}/g" '{}' ';'

#
# substitute any available local mirrors in the .repo files
#

/trait-expanded/trait-install/vmirmog \
    /tmp/mutate.vsys.mirrorlist.cfg \
    ${reposdir} \
    http://${mutate_webserver_ip}:${mutate_webserver_port}/mirrors/

rm -f /tmp/mutate.vsys.mirrorlist.cfg

echo -en "\n"
echo -en "##                                                                    ##\n"
echo -en "## status: mutate pre - fedora/x86 - complete                         ##\n"
echo -en "##                                                                    ##\n"
echo -en "########################################################################\n"
echo -en "########################################################################\n"
echo -en "\n"
