#!/bin/bash

progname="$( basename $0 )"
progdir=$( ( pushd $( dirname $0 ) > /dev/null 2>&1 ; \
    pwd ; popd > /dev/null 2>&1 ) )

username=zguest
usercomment="ZyX Guest User"
source ${progdir}/trait-options

useradd -c "$usercomment" $username
passwd -d $username > /dev/null

if [ -e /usr/share/zyx/face-icon.png ] ; then
    cp /usr/share/zyx/face-icon.png /home/${username}/.face
    chown ${username}:${username} /home/${username}/.face
fi

mkdir -p /home/${username}/.config/autostart
echo "X-GNOME-Autostart-enabled=false" >> /home/${username}/.config/autostart/gpk-update-icon.desktop
chown -R ${username}:${username} /home/${username}/.config
