#!/bin/bash
#
# trait installers assume they are run within a chroot to the target
# system, after the files have also been extracted to the root of the
# target system.

rundir=$( dirname $0 )
cd ${rundir}

rpm -qa --last > /var/log/sysinfo.rpmqalast.txt

for rpm in $( rpm -qa ); do 
    rpm -qi $rpm | \
	grep "Source RPM" | \
	sed -e 's/.*Source RPM: //' \
	>> /tmp/sysinfo.srpms
done 

cat /tmp/sysinfo.srpms \
    | sort \
    | uniq \
    | grep -v "(none)" \
    > /var/log/sysinfo.srpms

rm -f /tmp/sysinfo.srpms

