#!/bin/bash
#
# trait installers assume they are run within a chroot to the target
# system, after the files have also been extracted to the root of the
# target system.

rundir=$( dirname $0 )
cd ${rundir}

for rpm in $( rpm -qa ); do 
    rpm -qi $rpm | \
	grep "Source RPM" | \
	sed -e 's/.*Source RPM: //' \
	>> /tmp/sysinfo.srpms
done 

cat /tmp/sysinfo.srpms \
    | sort | uniq \
    > /var/log/sysinfo.srpms

rm -f /tmp/sysinfo.srpms

mkdir -p /VirOS.prime_rootfs/repo

pushd /VirOS.prime_rootfs/repo >> /var/log/sysinfo.srpms.log 2>&1
for rpm in $( < /var/log/sysinfo.srpms ); do
#    yumdownloader gcc >> /var/log/sysinfo.srpms.log 2>&1
# this worked
#    yumdownloader --source gcc >> /var/log/sysinfo.srpms.log 2>&1
# but this seemed to take forever, try with tee next time
#    yumdownloader --source ${rpm} >> /var/log/sysinfo.srpms.log 2>&1
#    yumdownloader --source ${rpm} 2>&1 | tee -a /var/log/sysinfo.srpms.log 
# XXX probably needs munging on the srpm from above (i.e. .srpm)
done
popd >> /var/log/sysinfo.srpms.log 2>&1
