#!/bin/bash
#
# viros trait post-install script for trait: compose.repos
#
# options:
# 
# mode=install|uninstall
#

##
## get runtime environment
##
progname="$( basename $0 )"
progdir=$( ( pushd $( dirname $0 ) > /dev/null 2>&1 ; \
    pwd ; popd > /dev/null 2>&1 ) )

mode=install
source ${progdir}/trait-options

if [ "x${mode}" == "xinstall" ]; then

# example for using a 3rd party repo via a repo release rpm
#
#    rpm -ivh /trait-expanded/trait-install/dmc*.rpm
#    cp /usr/share/dmcrpms/RPM-GPG-KEY.dmc \
#	/etc/pki/rpm-gpg/RPM-GPG-KEY.dmc
#    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY.dmc

    mv /etc/yum.repos.d /etc/yum.repos.d.not.compose.repos
    mv /etc/yum.conf /etc/yum.conf.not.compose.repos

    cp -a /etc/yum.repos.d.compose.repos /etc/yum.repos.d
    cp -a /etc/yum.conf.not.compose.repos /etc/yum.conf
    echo "reposdir=/etc/yum.repos.d.compose.repos" \
	>> /etc/yum.conf

elif [ "x${mode}" == "xuninstall" ]; then
#    rpm -e dmc-release-1-1

#    rm -f /etc/pki/rpm-gpg/RPM-GPG-KEY.dmc

    rm -rf /etc/yum.repos.d.compose.repos
    rm -rf /etc/yum.repos.d
    rm -f /etc/yum.conf

    mv /etc/yum.repos.d.not.compose.repos /etc/yum.repos.d
    mv /etc/yum.conf.not.compose.repos /etc/yum.conf

else
    echo "${progname}: error: fatal: unknown option mode=${mode}"
    exit 1
fi

exit 0
