#!/bin/bash
#
# ===========================================
# rliveinst - rebootless live media installer
# ===========================================
# version 0.2-2009.03.05
#
# Copyright 2007-2009 Douglas McClendon <dmc@filteredperception.org> 
# http://viros.org/guitarzyx
# License: GPLv3
#
# An example ALPHA quality liveCD can be found at http://gzyx.org
# 







if [ $# -lt 1 ]; then
    echo "usage: rliveinst <target_partition> [<target_swap_partition>]"
    exit 1
fi

kernelversion=$( uname -r )

if $( ! echo $1 | grep -q "^\/dev\/sd..$" ); then
    echo "rliveinst: sorry, only /dev/sdXY partitions are currently supported"
    exit 1
else
    targetdisklet=$( echo $1 |sed -e 's/\(\/dev\/sd\)\(.\)\(.\)/\2/' )
    targetpartnum=$( echo $1 |sed -e 's/\(\/dev\/sd\)\(.\)\(.\)/\3/' )
    gtargetpartnum=$(( $targetpartnum - 1 ))
    if [ $targetdisklet == "a" ]; then
	gtargetdisknum=0
    elif [ $targetdisklet == "b" ]; then
	gtargetdisknum=1
    elif [ $targetdisklet == "c" ]; then
	gtargetdisknum=2
    elif [ $targetdisklet == "d" ]; then
	gtargetdisknum=3
    else
	echo "rliveinst: sorry, only /dev/sd[abcd]X partitions are supported"
    fi
fi

if [ $# -eq 2 ]; then
    if $( ! echo $2 | grep -q "^\/dev\/sd..$" ); then
	echo "rliveinst: sorry, only /dev/sdXY partitions are currently supported"
	exit 1
    else

	echo "rliveinst: beginning install to target: ${1}"

	targetsdisklet=$( echo $2 |sed -e 's/\(\/dev\/sd\)\(.\)\(.\)/\2/' )
	targetspartnum=$( echo $2 |sed -e 's/\(\/dev\/sd\)\(.\)\(.\)/\3/' )
	gtargetspartnum=$(( $targetspartnum - 1 ))
	if [ $targetsdisklet == "a" ]; then
	    gtargetsdisknum=0
	elif [ $targetsdisklet == "b" ]; then
	    gtargetsdisknum=1
	elif [ $targetsdisklet == "c" ]; then
	    gtargetsdisknum=2
	elif [ $targetsdisklet == "d" ]; then
	    gtargetsdisknum=3
	else
	    echo "rliveinst: sorry, only /dev/sd[abcd]X partitions are supported"
	fi
    fi

    echo "rliveinst: setting swap filesystem flag on target partition"
    echo -en "t\n${targetspartnum}\n82\nw\n" | fdisk /dev/sd${targetsdisklet}
    
else
    echo "rliveinst: beginning install to target: ${1}"
fi


if [ "$( fdisk -l /dev/sd${targetdisklet} | grep sd${targetdisklet}${targetpartnum} | awk '{print $2}' )" == '*' ]; then 
    echo "rliveinst: target partition is already bootable"
else 
    echo "rliveinst: activating target partition"
    echo -en "a\n${targetpartnum}\nw\n" | fdisk /dev/sd${targetdisklet}
fi

echo "rliveinst: setting ext3 filesystem flag on target partition"
echo -en "t\n${targetpartnum}\n83\nw\n" | fdisk /dev/sd${targetdisklet}



if [ $# -eq 2 ]; then
    echo "rliveinst: initializing swap"
    swapoff -a > /dev/null 2>&1
    mkswap $2 > /dev/null 2>&1
    swapon $2 > /dev/null 2>&1
    echo -en "$2 swap swap defaults 0 0\n" >> /etc/fstab
fi

echo "rliveinst: loading mirror configuration"
dmsetup create --table "$( dmsetup table zyx-liveos-rw )" zyx-liveos-rw-copy
echo "0 $( blockdev --getsize /dev/mapper/zyx-liveos-rw-copy ) mirror core 2 32 sync 2 /dev/mapper/zyx-liveos-rw-copy 0 $1 0" | dmsetup reload zyx-liveos-rw

echo "rliveinst: activating mirror configuration"
dmsetup resume zyx-liveos-rw

echo "rliveinst: migrating live root filesystem"
done=0
while (( ! $done )); do
    percent_done=$( echo "scale=11;$( dmsetup status zyx-liveos-rw | awk '{print $7}' )" | bc -l )
    percent_done_display=$( echo "scale=2;(${percent_done} * 90 + 2) / 1.0" | bc -l )
    echo "rliveinst: installation progress - ${percent_done_display} %"
    if [ "$percent_done" = "1.00000000000" ]; then
	done=1
    else
	sleep 5
    fi
done

echo "rliveinst: unloading mirror configuration"
echo "0 $( blockdev --getsize $1 ) linear $1 0" | dmsetup reload zyx-liveos-rw
echo "rliveinst: installation progress - 92.50 %"

echo "rliveinst: deactivating mirror configuration"
dmsetup resume zyx-liveos-rw
echo "rliveinst: installation progress - 93.00 %"

echo "rliveinst: copying files from prime to actual root filesystem"
rm -f /boot/vmlinuz-${kernelversion} 
cp /mnt/.LiveOS/prime_rootfs/boot/vmlinuz.1 /boot/vmlinuz-${kernelversion}
cp $( readlink -f /usr/bin/zyx-live-iso-to-disk ) \
    /usr/bin/zyx-live-iso-to-disk.actual
rm -f /usr/bin/zyx-live-iso-to-disk
mv /usr/bin/zyx-live-iso-to-disk.actual \
    /usr/bin/zyx-live-iso-to-disk

echo "rliveinst: installation progress - 93.25 %"

echo "rliveinst: freeing livemedia resources: zyx-liveos-rw-copy"
dmsetup remove zyx-liveos-rw-copy

echo "rliveinst: freeing livemedia resources: /mnt/.LiveOS/ mounts"
umount -l /mnt/.LiveOS/precow_rootfs

echo "rliveinst: freeing livemedia resources: zyx-liveos-ro"
dmsetup remove zyx-liveos-ro

echo "rliveinst: freeing livemedia resources: overlay image loop device"
losetup -d /dev/zyx_root_overlay
losetup -d /dev/zyx_root_overlay_readonly

umount -l /mnt/.LiveOS/overlayfs

echo "rliveinst: freeing livemedia resources: ext3 os image loop device"
losetup -d /dev/zyx_root_base

umount -l /mnt/.LiveOS/container_rootfs

echo "rliveinst: freeing livemedia resources: squashfs image loop device"
losetup -d /dev/zyx_root_container
echo "rliveinst: installation progress - 94.00 %"

umount -l /mnt/.LiveOS/prime_rootfs

echo "rliveinst: expanding root filesystem to largest possible size"
resize2fs -p /dev/mapper/zyx-liveos-rw
echo "rliveinst: installation progress - 96.00 %"

echo "rliveinst: configuring /dev/root symlink"
rm -f /dev/root
ln -s ${1} /dev/root
echo "rliveinst: installation progress - 96.50 %"

echo "rliveinst: configuring fstab"
mv /etc/fstab /tmp/rliveinst.old.fstab

cat<<AEOF> /etc/fstab
$1 /                       ext3    defaults,noatime 0 0
devpts                  /dev/pts                devpts  gid=5,mode=620  0 0
tmpfs                   /dev/shm                tmpfs   defaults        0 0
proc                    /proc                   proc    defaults        0 0
sysfs                   /sys                    sysfs   defaults        0 0
$2                      swap                    swap    defaults        0 0

AEOF
echo "rliveinst: installation progress - 97.00 %"

echo "rliveinst: making initrd"
mkinitrd --preload=pata_via /boot/initrd-${kernelversion}.img ${kernelversion}
echo "rliveinst: installation progress - 98.50 %"

echo "rliveinst: configuring grub"
cat<<BEOF> /boot/grub/grub.conf
default=0
timeout=11
hiddenmenu
title *ZyX LiveOS (${kernelversion})
        root (hd${gtargetdisknum},${gtargetpartnum})
        kernel /boot/vmlinuz-${kernelversion} ro root=${1} quiet
        initrd /boot/initrd-${kernelversion}.img
BEOF
echo "rliveinst: installation progress - 99.00 %"

echo "rliveinst: installation progress - 99.50 %"

mv /etc/rc.d/init.d/functions \
    /etc/rc.d/init.d/functions.zyx_live
cp /etc/rc.d/init.d/functions.orig \
    /etc/rc.d/init.d/functions

mv /etc/rc.d/init.d/halt \
    /etc/rc.d/init.d/halt.zyx_live
cp /etc/rc.d/init.d/halt.orig \
    /etc/rc.d/init.d/halt

echo "rliveinst: installing grub bootloader"
cp /usr/share/grub/i386-redhat/*stage* /boot/grub/
echo -en "root (hd${gtargetdisknum},${gtargetpartnum})\nsetup (hd${gtargetdisknum})\n" | grub --batch
echo "rliveinst: installation progress - 100.00 %"


echo "rliveinst: you may now eject or remove the live media"
echo "rliveinst: installation complete, enjoy...                 -dmc"

exit 0




