#!/bin/bash

width=480
height=360

intro_text="\
   !!! WARNING WARNING WARNING !!!

This installation process will prompt for 
one or two selected disk partitions, which 
will then be wiped and used for this OS's
root filesystem, and optionally swap space.

Unlike traditional LiveCD installers, you
will not need to reboot after the
installation completes.  You will be able
to eject or remove the LiveOS media, and 
then continue normal computer operation 
without rebooting.  (pretty cool eh?)

This process *INCLUDES* overwriting the
bootloader with a new one.  You will have
to know grub configuration and basic system
administration in order to add other
preexisting bootable partitions other than
the one(s) being presently WIPED(!).
"

done_text="\
Congratulations!!!

The installation is complete.  With any 
luck, you should now be able to eject
the LiveCD or remove the LiveUSB safely,
and enjoy your newly installed system
without rebooting.
"

zenity --question \
    --width ${width} --height ${height} \
    --title "ZyX RLiveInst: Rebootless LiveOS Installer" \
    --text "$intro_text"
zrv=$?

if (($zrv)); then
    echo "zrliveinst: installation declined, goodbye!"
    exit 0
fi

partchoice=$( /usr/lib/zrliveinst/listparts | sort | zenity --list \
    --width ${width} --height ${height} \
    --title "ZyX RLiveInst: Choose Installation Destination Disk Volume" \
    --column "Installation Destination Disk Volume Options" \
    --text "Select a disk volume for installation from the list below:" )

if [ "x" == "x${partchoice}" ]; then
    echo "zrliveinst: installation declined, goodbye!"
    exit 0
fi

destpart=$( echo "$partchoice" | sed -e 's/.*\s--\s//' )

spartchoice=$( /usr/lib/zrliveinst/listparts | sort | zenity --list \
    --width ${width} --height ${height} \
    --title "ZyX RLiveInst: Choose Installation Swap Volume" \
    --column "Installation Swap Volume Options" \
    --text "Select a disk volume for swap from the list below, or cancel for none:" )

if [ "x" == "x${spartchoice}" ]; then
    echo "zrliveinst: swap declined"
    sdestpart="no"
    swap_subtext=""
else
    sdestpart=$( echo "$spartchoice" | sed -e 's/.*\s--\s//' )
    swap_subtext=" and $spartchoice"
fi

zenity --question \
    --width ${width} --height ${height} \
    --title "ZyX RLiveInst: The Rebootless LiveOS Installer" \
    --text "Are you SURE that you want to ERASE and REPLACE BOTH the BOOTLOADER AND the disk partition $partchoice${swap_subtext}???"
zrv=$?

if (($zrv)); then
    echo "zrliveinst: installation declined, goodbye!"
    exit 0
fi

zenity --question \
    --width ${width} --height ${height} \
    --title "ZyX RLiveInst: The Rebootless LiveOS Installer" \
    --text "Are you REALLY SURE that you want to ERASE and REPLACE BOTH the BOOTLOADER AND the disk partition $partchoice ???"
zrv=$?

if (($zrv)); then
    echo "zrliveinst: installation declined, goodbye!"
    exit 0
fi

if [ "x${sdestpart}" == "xno" ]; then
    /usr/sbin/rliveinst ${destpart} 2>&1 | \
	tee -a /var/log/rliveinst.log | \
	sed -u -e 's/.*-.//' -e 's/\s%$//' | \
	zenity --progress --width ${width} --height ${height} \
	--title "ZyX RLiveInst: Installation Progress" \
	--text "Rebootless LiveOS Installation in Progress..."
    zrv=$?
else
    /usr/sbin/rliveinst ${destpart} ${sdestpart} 2>&1 | \
	tee -a /var/log/rliveinst.log | \
	sed -u -e 's/.*-.//' -e 's/\s%$//' | \
	zenity --progress --width ${width} --height ${height} \
	--title "ZyX RLiveInst: Installation Progress" \
	--text "Rebootless LiveOS Installation in Progress..."
    zrv=$?
fi

if (($zrv)); then
    echo "zrliveinst: installation cancelled, goodbye!"
    exit 0
fi

zenity --info \
    --width ${width} --height ${height} \
    --title "ZyX RLiveInst: The Rebootless LiveOS Installer" \
    --text "$done_text"
