#!/bin/bash
#
# VirOS trait: F-ZyX.cleanup
#

echo "STATUS: removing fedora-release-notes"
rpm -e --nodeps fedora-release-notes

echo "STATUS: cleaning yum cache"
rm -rvf /var/cache/yum/*

echo "STATUS: cleaning /tmp"
rm -rvf /tmp/*

echo "STATUS: cleaning misc"
rm -f /root/vsys.runpost.log

# experimental workaround: grubby seems broken under qfakeroot/chroot
# todo: this should be its own trait
#echo "STATUS: removing old kernel"
#numkernels=$( rpm -qa --last | grep "^kernel-2.6" | wc -l )
#removekernels=$(( $numkernels - 1 ))
#while (( $removekernels )); do
#    removekernel=$( rpm -qa --last | grep "^kernel-2.6" | tail -1 | awk '{print $1}' )
#    rpm -e "${removekernel}"
#    removekernels=$(( ${removekernels} - 1 ))
#done
