#!/usr/bin/env bash
#!/bin/bash
#
# fedora installer only has /usr/bin/bash, fedora installed only has
# /bin/bash.  go figure.
#
#############################################################################
#
# runpre: script that is run early in a VirOS fedora qrap install 
#
#############################################################################
#
# Copyright 2007 Douglas McClendon <dmc AT filteredperception DOT org>
#
#############################################################################
#
#This file is part of VirOS.
#
#    VirOS is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    VirOS is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with VirOS.  If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################

watchfiles="\
    /tmp/anaconda.log \
    /mnt/sysimage/root/install.log \
    /mnt/sysimage/root/install.log.syslog \
    /tmp/vsys.runpre.log \
    /mnt/sysimage/root/vsys.runpost.log \
    /mnt/sysimage/var/log/vrun.generate \
    "


function annotailhelper {
    while ((1)); do
	read
	prefix="TAILLOG : $1 : $( date +%H:%M:%S ) : "
	echo "${prefix}${REPLY}"
    done
}

function waitntail {

    timeout=$(( 6 * 60 * 12 ))
    counter=0
    while [ ! -f $1 ]; do
	sleep 10
	counter=$(( $counter + 1 ))
	if [ $counter -gt $timeout ]; then
	    echo "waitntail $1 TIMED OUT"
	    return
	fi
    done

    tail --lines=9999 -f $1 | annotailhelper $1
}

function sendlog {
    cat >> /tmp/vsys.sendlog
}

for logfile in ${watchfiles}; do
    echo "debug logfile is $logfile"
    ( waitntail $logfile | sendlog ) >> /tmp/vsys.runpre.log 2>&1 &
done

tail --lines=9999 -f /tmp/vsys.sendlog > /dev/ttyS0 2>&1 &

