/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_splashscreen (void)
{
  GtkWidget *splashscreen;
  GtkWidget *vbox1;
  GtkWidget *top_image;
  GtkWidget *hbox1;
  GtkWidget *left_image;
  GtkWidget *progressbar;
  GtkWidget *right_image;
  GtkWidget *bottom_image;

  splashscreen = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (splashscreen), _("kablui initialization"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (splashscreen), vbox1);

  top_image = create_pixmap (splashscreen, NULL);
  gtk_widget_show (top_image);
  gtk_box_pack_start (GTK_BOX (vbox1), top_image, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  left_image = create_pixmap (splashscreen, NULL);
  gtk_widget_show (left_image);
  gtk_box_pack_start (GTK_BOX (hbox1), left_image, TRUE, TRUE, 0);

  progressbar = gtk_progress_bar_new ();
  gtk_widget_show (progressbar);
  gtk_box_pack_start (GTK_BOX (hbox1), progressbar, FALSE, FALSE, 1);

  right_image = create_pixmap (splashscreen, NULL);
  gtk_widget_show (right_image);
  gtk_box_pack_start (GTK_BOX (hbox1), right_image, TRUE, TRUE, 0);

  bottom_image = create_pixmap (splashscreen, NULL);
  gtk_widget_show (bottom_image);
  gtk_box_pack_start (GTK_BOX (vbox1), bottom_image, TRUE, TRUE, 0);

  g_signal_connect ((gpointer) splashscreen, "destroy_event",
                    G_CALLBACK (on_splashscreen_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) splashscreen, "key_press_event",
                    G_CALLBACK (on_splashscreen_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) splashscreen, "configure_event",
                    G_CALLBACK (on_splashscreen_configure_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (splashscreen, splashscreen, "splashscreen");
  GLADE_HOOKUP_OBJECT (splashscreen, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (splashscreen, top_image, "top_image");
  GLADE_HOOKUP_OBJECT (splashscreen, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (splashscreen, left_image, "left_image");
  GLADE_HOOKUP_OBJECT (splashscreen, progressbar, "progressbar");
  GLADE_HOOKUP_OBJECT (splashscreen, right_image, "right_image");
  GLADE_HOOKUP_OBJECT (splashscreen, bottom_image, "bottom_image");

  return splashscreen;
}

