#!/bin/bash

parts=$( find /dev/disk/by-id -type l -print )
numparts=0
for part in $parts; do
    part_real=$( readlink -e $part )
    notdup=1
    for (( i=1 ; ${i} <= ${numparts} ; i=$(($i + 1)) )); do
	if [ "$part_real" == "${rpartlist[$i]}" ]; then
	    notdup=0
	fi
    done
    if (($notdup)); then
	numparts=$(( $numparts + 1 ))
	rpartlist[${numparts}]=$part_real
	partlist[${numparts}]=$part
    fi
done

for (( i=1 ; ${i} <= ${numparts} ; i=$(($i + 1)) )); do
    echo "$( basename ${partlist[$i]} ) -- ${rpartlist[$i]}"
done
