#!/bin/bash

##
## get runtime environment
##
progname="$( basename $0 )"
progdir=$( ( pushd $( dirname $0 ) > /dev/null 2>&1 ; \
    pwd ; popd > /dev/null 2>&1 ) )

autologin=false
user=none
source ${progdir}/trait-options

if [ "x${autologin}" == "xtrue" ]; then
    cp /etc/gdm/custom.conf /tmp/zyx-live.custom.conf.$$
    cat /tmp/zyx-live.custom.conf.$$ | \
	grep -v "AutomaticLoginEnable=" | \
	grep -v "AutomaticLogin=" | \
	sed -e "s/^\[daemon\]/\[daemon\]\nAutomaticLoginEnable=true\nAutomaticLogin=${user}/" | \
	sed -e "s/^\[debug\]/\[debug\]\nEnabled=true/" \
	> /etc/gdm/custom.conf

    if (! grep -q "\[daemon\]" /etc/gdm/custom.conf); then
	cp /tmp/zyx-live.custom.conf.$$ /etc/gdm/custom.conf
	cat << EOF >> /etc/gdm/custom.conf

[daemon]
# wow, with f10 upstream, this is back, it just sucks (too much) now
# though theoretically upstream has fixed that in f11
#AutomaticLoginEnable=true
#AutomaticLogin=${user}
TimedLoginEnable=true
TimedLogin=${user}
TimedLoginDelay=11
EOF
    fi

    if (! grep -q "\[debug\]" /etc/gdm/custom.conf); then
	cp /tmp/zyx-live.custom.conf.$$ /etc/gdm/custom.conf
	cat << EOF >> /etc/gdm/custom.conf

[debug]
#Enabled=true
Enabled=false
EOF
    fi



    rm -f /tmp/zyx-live.custom.conf.$$ 
fi

# this was probably never a real solution, delete as soon as things stabalize
#
# .dmrc is a possible workaround for a known gdm bug (hence debug enabled above)
#echo -en "\n\n" > /home/${username}/.dmrc
#chown ${username}:${username} /home/${username}/.dmrc
#if [ -e /usr/share/zyx/face-icon.png ] ; then
#    cp /usr/share/zyx/face-icon.png /home/${username}/.face
#    chown ${username}:${username} /home/${username}/.face
#fi

