#!/bin/bash

cat <<EOF >> /etc/rc.d/rc.local


#############################################################################
#
# This worksaround the pulseaudio HEALTH HAZARD bug
# 
zyx-chronic-fixup.pulseaudio.flatvolumes
#
#############################################################################


EOF