#!/bin/bash

rpm -e --nodeps fedora-logos
yum -y install generic-logos

sed -i \
    -e 's/fedora\-logo\-icon/\/usr\/share\/pixmaps\/zyx\.liveinst\.64\.png/' \
    /usr/share/applications/liveinst.desktop

mv /usr/sbin/liveinst /usr/sbin/liveinst.orig
cat /usr/sbin/liveinst.orig | grep -v "^export ANACONDA" > /tmp/liveinst
cat <<EOF >/usr/sbin/liveinst
export ANACONDA_PRODUCTNAME=\$( cat /etc/zyx-release | sed -e 's/\srelease.*//' )
export ANACONDA_PRODUCTVERSION=\$( cat /etc/zyx-release | sed -e 's/.*release\s//' | sed -e 's/\s(.*//' )
export ANACONDA_BUGURL="http://example.com/bugz"
EOF

cat /tmp/liveinst >> /usr/sbin/liveinst
chmod 755 /usr/sbin/liveinst
rm -f /tmp/liveinst

