#!/bin/bash

# viros trait post-install script for trait: software
#
# options/usage
#
# install=<package/list>
# erase=<package/list>
#
# where arg is a package/list that 'yum -y install <package/list>' would
# understand.
#
# e.g. 
# --addtrait=software::addpackages=livecd-tools

##
## get runtime environment
##
progname="$( basename $0 )"
progdir=$( ( pushd $( dirname $0 ) > /dev/null 2>&1 ; \
    pwd ; popd > /dev/null 2>&1 ) )

echo "${progname}: BEGIN XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

echo "${progname}: software managment trait options:"
cat ${progdir}/trait-options

source ${progdir}/trait-options

if [ "${update}" == "yes" ]; then
    echo "${progname}: updating system software ..."
    yum -y --disableplugin=refresh-packagekit,presto --enablerepo=updates,sl-updates update glibc
    yum -y --disableplugin=refresh-packagekit,presto --enablerepo=updates,sl-updates update yum
    yum -y --disableplugin=refresh-packagekit,presto --enablerepo=updates,sl-updates update
    yum -y --disableplugin=refresh-packagekit,presto --enablerepo=updates,sl-updates update
    echo "${progname}: done updating system software."
fi

if [ "${install}" != "" ]; then
    echo "${progname}: installing software: $install"
    yum -y --disableplugin=refresh-packagekit,presto --enablerepo=updates,sl-updates install $install
    echo "${progname}: done installing software: $install"
fi

if [ "${groupinstall}" != "" ]; then
    echo "${progname}: installing software group: $groupinstall"
#    yum -y --disableplugin=refresh-packagekit,presto groupinstall $groupinstall
    yum \
	-y \
	--disableplugin=refresh-packagekit,presto \
	--enablerepo=updates,sl-updates \
	install \
	$( repoquery -g -l --grouppkgs=all "${groupinstall}" )
    echo "${progname}: done installing software group: $groupinstall"
fi

if [ "${erase}" != "" ]; then
    echo "${progname}: uninstalling software: $erase"
    yum -y --disableplugin=refresh-packagekit,presto erase $erase
    echo "${progname}: done uninstalling software: $erase"
fi

echo "${progname}: END XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

exit 0

