#!/bin/bash

##
## get runtime environment
##
progname="$( basename $0 )"
progdir=$( ( pushd $( dirname $0 ) > /dev/null 2>&1 ; \
    pwd ; popd > /dev/null 2>&1 ) )

user=none
source ${progdir}/trait-options

# workaround some race condition easily triggered by running under qemu
# https://bugzilla.redhat.com/show_bug.cgi?id=464385
# todo: get bug above changed to f11 as is already mentioned in comments
gconftool-2 \
    --direct \
    --config-source \
    xml:readwrite:/etc/gconf/gconf.xml.defaults \
    --set \
    --type bool \
    /apps/gnome_settings_daemon/plugins/keyboard/active \
    false