#!/bin/bash
yum -y --disableplugin=refresh-packagekit,presto --enablerepo=updates update glibc
yum -y --disableplugin=refresh-packagekit,presto --enablerepo=updates update yum
yum -y --disableplugin=refresh-packagekit,presto --enablerepo=updates update grubby
yum -y --disableplugin=refresh-packagekit,presto --enablerepo=updates update kernel
