#!/bin/bash
yum -y --disableplugin=refresh-packagekit,presto --enablerepo=updates,sl-updates update glibc
yum -y --disableplugin=refresh-packagekit,presto --enablerepo=updates,sl-updates update yum
yum -y --disableplugin=refresh-packagekit,presto --enablerepo=updates,sl-updates update grubby
yum -y --disableplugin=refresh-packagekit,presto --enablerepo=updates,sl-updates update kernel
