#!/bin/bash

##
## get runtime environment
##
progname="$( basename $0 )"
progdir=$( ( pushd $( dirname $0 ) > /dev/null 2>&1 ; \
    pwd ; popd > /dev/null 2>&1 ) )

/sbin/chkconfig --add zyx-live

# testing no acpi=force
#cp /boot/grub/grub.conf  /boot/grub/grub.conf.stock
#cat /boot/grub/grub.conf.stock | \
#    sed -e 's/^\(\s*kernel.*\)$/\1 acpi=force/' \
#    > /boot/grub/grub.conf

mkdir -p /var/trash/etc/event.d
cp -a /etc/event.d/rcS /var/trash/etc/event.d/
# the meat of this is currently just aesthetic, and lvm (and md if cfg)
sed -i \
    -e 's/rc\.sysinit/init\.d\/rc\.sysinit\.zyx/' \
    /etc/event.d/rcS

cat <<EOF >> /etc/rc.d/rc.local
#
# zyx misc
#

#####################################################################
#
# Run ZyX rc.local scriptlets
#
# E.g. customizations that may get overwritten on package update
# 
#
for script in \$( ls -1A /etc/zyx/chronic.d ); do
    if [ -x "/etc/zyx/chronic.d/\${script}" ]; then
        echo "ZyX: running cronic fixup bootscripts at \$(date)" >> /var/log/zyx-chronic 2>&1
        "/etc/zyx/chronic.d/\${script}" >> /var/log/zyx-chronic 2>&1
    fi
done
#####################################################################

EOF


cat <<EOF >> /etc/sudoers
ALL guitar-zyx= NOPASSWD: /usr/sbin/pm-hibernate
ALL guitar-zyx= NOPASSWD: /usr/sbin/pm-suspend
EOF


for user in $( ls -1A /home ); do 
    cp -av /etc/skel/* /home/${user}/
    chown -R ${user}:${user} /home/${user}
done

