#!/bin/bash

progname="$( basename $0 )"
progdir=$( ( pushd $( dirname $0 ) > /dev/null 2>&1 ; \
    pwd ; popd > /dev/null 2>&1 ) )

/sbin/chkconfig --add zyx-live

lokkit -f --quiet --nostart --enabled
lokkit -q -p 24642:tcp

cp /boot/grub/grub.conf  /boot/grub/grub.conf.stock
cat /boot/grub/grub.conf.stock | \
    sed -e 's/^\(\s*kernel.*\)$/\1 acpi=force/' \
    > /boot/grub/grub.conf



mkdir -p /var/trash/etc/event.d
cp -a /etc/event.d/rcS /var/trash/etc/event.d/
sed -i \
    -e 's/rc\.sysinit/init\.d\/rc\.sysinit\.zyx/' \
    /etc/event.d/rcS

mv /etc/event.d/tty[1-3] /var/trash/etc/event.d/

cat <<EOF >> /etc/rc.d/rc.local

if [ -b /dev/sda ]; then
    hdparm -B 254 /dev/sda
fi

modprobe kqemu > /dev/null 2>&1
chmod 666 /dev/kqemu > /dev/null 2>&1

chvt 4

EOF
