#!/bin/bash

##
## get runtime environment
##
progname="$( basename $0 )"
progdir=$( ( pushd $( dirname $0 ) > /dev/null 2>&1 ; \
    pwd ; popd > /dev/null 2>&1 ) )

user=none
source ${progdir}/trait-options

##
## install dependencies
##
yum -y install unzip wmctrl

